{% set name = "icfree" %}
{% set version = "2.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/brsynth/icfree-ml/archive/{{ version }}.tar.gz
  sha256: 7ea76c71098b86f562fd676c31b440da86d2f1c83c70b601eea58d4e28cce408

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install -vv .

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8,<3.12
    - pandas
    - pydoe2

test:
  source_files:
    - tests
  imports:
    - {{ name|lower }}
  requires:
    - pytest
  commands:
    - python -m {{ name|lower }} --help
    - python -m pytest

about:
  home: https://github.com/brsynth/icfree-ml
  summary: Design of experiments (DoE) and machine learning for cell-free
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - guillaume-gricourt
    - breakthewall
    - tduigou
