{% set name = "icfree" %}
{% set version = "2.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/brsynth/icfree-ml/archive/{{ version }}.tar.gz
  sha256: 63b919033f87d0322d8178c21a9f94a3519849d8b766bddc04d6bd31ed11f220

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install -vv .

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8,<3.12
    - numpy
    - pandas
    - pydoe2
    - brs_utils
    - scikit-learn

test:
  source_files:
    - tests
  imports:
    - {{ name|lower }}
  requires:
    - pytest
  commands:
    - python -m {{ name|lower }} --help
    - python -m pytest

about:
  home: https://github.com/brsynth/icfree-ml
  summary: Design of experiments (DoE) and machine learning for cell-free
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - guillaume-gricourt
    - breakthewall
    - tduigou
    - yorgomoubayed
